### ISSUE TITLE
[advice]how about add an volume?

### ISSUE THREAD

**Issue by Tiaonmmn** [Asuri-Team/ctf-xinetd#3]
When using tcpdump to capture traffic,it will save contents when container stops.But if you start the container,it would clean original capture.pcap.So how about add an volume on Dockerfile?
Just a little advice,don't mind it.

**Comment by summershrimp** [comment]
Your advice is useful, I will add a more solid traffic capture method later, maybe change tcpdump to tshark.
For now, you can manually add `-v your_dump_volume:/var/lib/tcpdump` to your `docker create`  or `docker run` command to prevent data loss.

**Comment by summershrimp** [comment]
Use [asuri/ctf-xinetd:1.0.1](https://hub.docker.com/r/asuri/ctf-xinetd/tags/)
